config/routes.rb
Techradarcommunity::Application.routes.draw do

  get "user_company_roles/new"

  get "user_company_roles/delete"

  match "/auth/:provider/callback" => "sessions#create", :as => :auth
  match "/signout" => "sessions#destroy", :as => :signout
  match "/login" => "sessions#login", :as => :login

  resources :companies

  scope ":company" do
    root to: "radar#index", as: :tenant_root

    get 'radar' => "radar#index"

    resources :products do
      resources :comments
      resources :product_technologies, path: 'usage', only: [:create] #, as: 'usage'
    end
    resources :technologies do
      resources :comments
      resources :recommends
    end
    resources :product_technologies

    resources :roles do
      resources :user_company_roles, as: 'members', path: 'members', only: [:create, :delete]
    end
    resources :categories
    resources :recommendations
    resources :states

  end

  root :to => 'home#index'

end

app/models/technology.rb
class Technology < ActiveRecord::Base
  acts_as_tenant(:company)

  belongs_to :company
  belongs_to :category
  has_many :product_technologies, :dependent => :delete_all
  has_many :products, :through => :product_technologies
  has_many :comments, :as => :commentable, :dependent => :delete_all
  has_many :recommends, :as => :recommendable
  attr_accessible :category_id, :description, :name, :summary

  validates :category, :name, :presence => true

  before_destroy :confirm_orphan

	def products_using_this
    products.map {|x| 
      pt = product_technologies
        .where(:product_id => x.id)
        .order("created_at DESC")
        .first

      { name: x.name, product: x, state: pt.state.name }
    }
	end

	def products_not_using_this
		#return Product.find(:all) if product_technologies.count == 0
		Product.where('id not in (?)', product_technologies.map(&:product_id))
	end

  def orphan?
    !(connected_products? || connected_recommendations?)
  end

  def active?
    deleted_at.nil?
  end

  def deleted?
    !active?
  end

  protected

  def confirm_orphan
  	is_orphan = true

    if connected_products?
    	is_orphan = false
    	errors.add(:base, 'The technology has connected products, remove them before deleting the technology.')
    end

    if connected_recommendations?
    	is_orphan = false
    	errors.add(:base, 'The technology has connected recommendations, remove them before deleting the technology.' )
    end

    return is_orphan
  end

  def connected_products?
    products.count > 0
  end

  def connected_recommendations?
    recommends.count > 0
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < TenantController
  before_filter only: [:create, :new, :edit, :update] {has_permission_to? 'create_technologies'}
  before_filter only: [:destroy] {has_permission_to? 'delete_technologies'}

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all(:conditions => 'deleted_at IS NULL')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @technologies }
    end
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
    @technology = Technology.find(params[:id], :include => :product_technologies)
    if @technology.product_technologies.count > 0
      @products_using_this = @technology.products_using_this
      @products_not_using_this = @technology.products_not_using_this
      #@products_using_this = @technology.product_technologies
      #@products_not_using_this = Product.where('id not in (?)', @technology.product_technologies.map(&:product_id).join(','))
    else
      @products_using_this = [] # use 'none' in Rails 4
      @products_not_using_this = Product.find(:all)
    end
    
    @commentable = @technology
    @comments = @commentable.comments
    @comment = Comment.new

    @recommendable = @technology
    @recommends = @recommendable.recommends
    @recommend = Recommend.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @technology }
    end
  end

  # GET /technologies/new
  # GET /technologies/new.json
  def new
    @technology = Technology.new
    @categories = Category.find(:all)

    if @categories.count == 0
      flash[:error] = 'You need to create a category before you can create a technology'
      redirect_to new_category_path and return
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @technology }
    end
  end

  # GET /technologies/1/edit
  def edit
    @technology = Technology.find(params[:id])
    @categories = Category.find(:all)

    if @technology.deleted?
      respond_to do |format|
        flash[:error] = 'Technology is marked as deleted, so cannot be modified'
        format.html { redirect_to @technology }
        format.json { render nothing: true, status: :method_not_allowed }
      end
    end
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(params[:technology])
    @categories = Category.find(:all)

    respond_to do |format|
      if @technology.save
        flash[:success] = 'Technology was successfully created.'
        format.html { redirect_to @technology }
        format.json { render json: @technology, status: :created, location: @technology }
      else
        format.html { render action: "new" }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /technologies/1
  # PUT /technologies/1.json
  def update
    @technology = Technology.find(params[:id])
    @categories = Category.find(:all)

    respond_to do |format|

      if @technology.active?
        if @technology.update_attributes(params[:technology])
          flash[:success] = 'Technology was successfully updated.'
          format.html { redirect_to @technology }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @technology.errors, status: :unprocessable_entity }
        end
      else
        flash[:error] = 'Technology is marked as deleted, so cannot be modified'
        format.html { redirect_to @technology }
        format.json { render json: @technology.errors, status: :method_not_allowed }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology = Technology.find(params[:id])
    technology_name = @technology.name

    if @technology.active?
      @technology.deleted_at = DateTime.now

      respond_to do |format|
        #if @technology.destroy
        if (@technology.orphan?)
          success = @technology.destroy
        else
          success = @technology.save
        end
        if success
          flash[:notice] = "#{technology_name} deleted"
          format.html { redirect_to technologies_url }
          format.json { head :no_content }
        else
          flash[:error] = 'Technology has product connections or recommendations'
          format.html { redirect_to @technology }
          format.json { render json: @technology.errors }
        end
      end
    else
      respond_to do |format|
        flash[:error] = 'Technology has already been marked as deleted'
        format.html { redirect_to @technology }
        format.json { render json: @technology.errors, status: :method_not_allowed }
      end
    end
  end

end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_for(@technology, :html => {:class => "custom"}) do |f| %>
  <fieldset>
    <legend>Technology</legend>

    <% if @technology.errors.any? %>
      <div data-alert class="alert-box alert">
        <ul>
        <% @technology.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>

        <a href="#" class="close">&times;</a>
      </div>
    <% end %>

    <div class="row">
      <div class="large-12 columns">
        <%= f.label :category %>
        <%= f.select :category_id, options_for_select(@categories.map{|x| [x.name.titleize.pluralize, x.id] }), class: ['custom','dropdown','medium'] %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :summary %>
        <small><%= md_help %></small>
        <%= f.text_area :summary %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :description %>
        <small><%= md_help %></small>
        <%= f.text_area :description %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.submit class: 'button' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing technology</h1>

<div class="button-bar">
	<div class="button-group">
		<%= link_to 'Back to technologies', technologies_path, class: 'small secondary button' %>
	</div>
	<div class="button-group">
		<%= link_to 'Cancel', @technology, class: 'small button' %>
	</div>
</div>

<%= render 'form' %>

app/views/technologies/index.html.erb
<h1>Technologies</h1>

<div class="button-bar">
  <ul class="button-group">
    <li><%= link_to 'Create Technology', new_technology_path, :class => ['small', 'button'] %></li>
  </ul>
</div>

<% if @technologies.count > 0 %>
<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Summary</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.category.name.singularize.titleize %></td>
        <td><%= link_to technology.name, technology %></td>
        <td><%= md technology.summary.to_s %></td>
        <td>
          <%= link_to_if has_permission_to?('create_technologies'), image_tag('pencil.png', alt: 'Edit technology', title: 'Edit technology' ), edit_technology_path(technology), class: 'small secondary inline button' %>
          <%= link_to_if has_permission_to?('delete_technologies'), image_tag('delete.png', alt: 'Delete technology', title: 'Delete technology' ), technology, method: :delete, data: { confirm: 'Are you sure?' }, class: 'small secondary inline button' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p class="secondary alert-box">There are no technologies yet<% if has_permission_to?('create_technologies') %>&hellip; <%= link_to 'create one', new_technology_path %><% end %>.</p>
<% end %>

app/views/technologies/new.html.erb
<h1>New technology</h1>

<div class="button-bar">
	<div class="button-group">
		<%= link_to 'Back to technologies', technologies_path, class: 'small secondary button' %>
	</div>
</div>

<%= render 'form' %>

app/views/technologies/show.html.erb
<div class="button-bar">
	<div class="button-group">
		<%= link_to 'Back', technologies_path, class: 'small secondary button' %>
	</div>
	<% if @technology.active? && logged_in? %>
	<div class="button-group">
		<%= link_to_if has_permission_to?('create_technologies'), 'Edit', edit_technology_path(@technology), class: 'small button' %>
		<%= link_to_if has_permission_to?('delete_technologies'), 'Delete', @technology, method: :delete, data: { confirm: 'Are you sure?' }, class: 'small alert button' %>
	</div>
	<% end %>
</div>

<h2 class="subheader"><%= @technology.category.name.singularize %></h2>

<% if @technology.deleted? %>
	<p class="alert-box">This technology has been deleted so it's readonly.</p>
<% end %>

<div itemscope itemtype="http://schema.org/Thing" class="row">
	<div class="large-8 columns">

		<h3 itemprop="name"><%= @technology.name %></h3>
		<% if @technology.recommends.count > 0 %>
			<p>Current recommendation: <strong style="color: blue;"><%= @technology.recommends.last.recommendation.name.titleize %></strong></p>
		<% end %>

		<% unless @technology.summary.to_s.empty? %>
			<div itemprop="description">
			  <%= md @technology.summary.to_s %>
			</div>
		<% end %>

		<% unless @technology.description.to_s.empty? %>
			<div>
			  <%= md @technology.description.to_s %>
			</div>
		<% end %>

		<% if @technology.recommends.count > 0 || logged_in? %>
			<h4 class="subheader">Recommendations</h4>

			<%= render :partial => 'recommends/recommends' %>
			<% if has_permission_to?('post_recommendations') %>
				<%= render :partial => 'recommends/form' unless @technology.deleted? %>
			<% end %>
		<% end %>

		<% if @technology.comments.count > 0 || logged_in? %>
			<h4 class="subheader">Comments</h4>

			<%= render :partial => 'comments/comments' %>
			<%= render :partial => 'comments/form' unless @technology.deleted? %>
		<% end %>
	</div>

	<div class="large-4 columns">
		<% if !@products_using_this.empty? && @products_using_this.count > 0 %>
			<div class="panel">
				<h5>Products using this</h5>
				<ul class="no-bullet">
					<% @products_using_this.each do |pt| %>
						<li><%= link_to pt[:name], pt[:product] %> <em>(<%= pt[:state] %>)</em></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<% if @products_not_using_this.count > 0 && @technology.active? %>
		<div class="panel">
			<h5>Products not using this yet</h5>
				<ul class="no-bullet">
					<% @products_not_using_this.each do |product| %>
						<li><%= link_to product.name, product %></li>
					<% end %>
			</div>
		<% end %>
	</div>

</div>