config/routes.rb
Techradarcommunity::Application.routes.draw do

  get "user_company_roles/new"

  get "user_company_roles/delete"

  match "/auth/:provider/callback" => "sessions#create", :as => :auth
  match "/signout" => "sessions#destroy", :as => :signout
  match "/login" => "sessions#login", :as => :login

  resources :companies

  scope ":company" do
    root to: "radar#index", as: :tenant_root

    get 'radar' => "radar#index"

    resources :products do
      resources :comments
      resources :product_technologies, path: 'usage', only: [:create] #, as: 'usage'
    end
    resources :technologies do
      resources :comments
      resources :recommends
    end
    resources :product_technologies

    resources :roles do
      resources :user_company_roles, as: 'members', path: 'members', only: [:create, :delete]
    end
    resources :categories
    resources :recommendations
    resources :states

  end

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  acts_as_tenant(:company)

  belongs_to :company
  has_many :product_technologies, :dependent => :delete_all
  has_many :technologies, :through => :product_technologies
  has_many :states, :through => :product_technologies
  has_many :comments, :as => :commentable, :dependent => :delete_all
  attr_accessible :name
  
  validates :name, :presence => true

  #before_destroy :confirm_orphan

  def used_technologies
    product_technologies
      .select("technology_id, max(date(created_at)), state_id ")
      .group("technology_id")



    technologies.map {|x| 
      pt = product_technologies
        .where(:technology_id => x.id)
        .order("created_at DESC")
        .first

      { name: x.name, product: x, state: pt.state.name }
    }

  end

  def unused_technologies
    return Technology.find(:all) if product_technologies.count == 0
    Technology.where('id not in (?)', product_technologies.map(&:technology_id).reject! { |c| c.nil? }.join(','))
  end

  protected

	def confirm_orphan
  	is_orphan = true

    if technologies.count > 0
    	is_orphan = false
    	errors.add(:base, 'The technology has connected technologies, remove them before deleting the product.')
    end

    if comments.count > 0
    	is_orphan = false
    	errors.add(:base, 'The product has connected comments, remove them before deleting the product.' )
    end

    return is_orphan
	end

end

app/controllers/products_controller.rb
class ProductsController < TenantController
  before_filter only: [:create, :new, :edit, :update] {has_permission_to? 'create_products'}
  before_filter only: [:destroy] {has_permission_to? 'delete_products'}


  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id], :include => :product_technologies)
    @product_technology = ProductTechnology.new product_id: @product.id #@product.product_technologies.new

    @commentable = @product
    @comments = @commentable.comments
    @comment = Comment.new

    @technologies = Technology.all # @product.unused_technologies

    @states = State.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        flash[:success] = 'Product was successfully created.'
        format.html { redirect_to @product }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        flash[:success] = 'Product was successfully updated.'
        format.html { redirect_to @product }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    product_name = @product.name
    @product.destroy

    respond_to do |format|
      if @product.destroy
        flash[:error] = "#{product_name} deleted"
        format.html { redirect_to products_url }
        format.json { head :no_content }
      else
        flash[:error] = 'Product has connections or recommendations. Remove these before deletion'
        format.html { redirect_to @product }
        format.json { render json: @product.errors }
      end
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:class => "custom"}) do |f| %>
  <fieldset>
    <legend>Product</legend>
  
    <% if @product.errors.any? %>
      <div data-alert class="alert-box alert">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>

        <a href="#" class="close">&times;</a>
      </div>
    <% end %>

    <div class="row">
      <div class="large-12 columns">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.submit class: 'button' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/products/_usage.html.erb
<% if Technology.count > 0 %>
<%= form_for([@product, @product_technology], :html => {:class => "custom"}) do |f| %>

  <%#= f.hidden_field :product_id %>

  <fieldset>
    <legend>New technology usage</legend>

    <% if @product_technology.errors.any? %>
      <div data-alert class="alert-box alert">
        <ul>
        <% @product_technology.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>

        <a href="#" class="close">&times;</a>
      </div>
    <% end %>

    <div class="row">
      <div class="large-6 columns">
        <%= f.label :technology_id %>
        <%= f.select :technology_id, options_for_select(@technologies.map{|x| [x.name, x.id] }), class: ['medium', 'custom', 'dropdown'] %>
      </div>
      <div class="large-5 columns">
        <%= f.label :state_id %>
        <%= f.select :state_id, options_for_select(@states.map{|x| [x.name.titleize, x.id] }), class: ['small', 'custom', 'dropdown'] %>
      </div>
      <div class="large-1 columns">
        <br />
        <%= f.submit "Add", class: 'small expand button' %>
      </div>
    </div>

  </fieldset>
<% end %>
<% else %>
  <p><em>There are no technologies available to be assigned<% if has_permission_to?('create_technologies') %>&hellip; <%= link_to 'create one', new_technology_path %><% end %>.</em></p>
<% end %>

app/views/products/_usages.html.erb
<% if @product.product_technologies.count > 0 %>
	<div class="striped bordered table large-12 columns">
	<% @product.product_technologies.order("created_at DESC").each do |usage| %>

	  <div class="row">
	  	<div class="large-6 columns">
	    	<%= link_to usage.technology.name, usage.technology %>
	  	</div>
	  	<div class="large-3 columns">
	    	<%= usage.state.name %>
	  	</div>
	  	<div class="large-3 columns">
		  	<time datetime="<%= usage.created_at.strftime('%FT%H:%M:S%Z') %>"><%= usage.created_at.strftime('%F %H:%M') %></time>
	  	</div>
	  </div>
	<% end %>
	</div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<div class="button-bar">
	<div class="button-group">
		<%= link_to 'Back to products', products_path, class: 'small secondary button' %>
	</div>
	<div class="button-group">
		<%= link_to 'Cancel', @product, class: 'small button' %>
	</div>
</div>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>

<div class="button-bar">
  <ul class="button-group">
    <% if has_permission_to?('create_products') %>
      <li><%= link_to 'Create Product', new_product_path, :class => ['small', 'button'] %></li>
    <% end %>
  </ul>
</div>

<% if @products.count > 0 %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product %></td>
        <td>
          <%= link_to_if has_permission_to?('create_products'), image_tag('pencil.png', alt: 'Edit product', title: 'Edit product' ), edit_product_path(product), class: 'small secondary inline button' %>
          <%= link_to_if has_permission_to?('delete_products'), image_tag('delete.png', alt: 'Delete product', title: 'Delete product' ), product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'small secondary inline button' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p class="secondary alert-box">There are no products yet<% if has_permission_to?('create_products') %>&hellip; <%= link_to 'create one', new_product_path %><% end %>.</p>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<div class="button-bar">
	<div class="button-group">
		<%= link_to 'Back to categories', products_path, class: 'small secondary button' %>
	</div>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="button-bar">
	<div class="button-group">
		<%= link_to 'Back', products_path, class: 'small secondary button' %>
	</div>
	<% if logged_in? %>
	<div class="button-group">
	  <% if has_permission_to?('create_products') %>
        <%= link_to 'Edit', edit_product_path(@product), class: 'small button' %>
	  <% end %>
      <% if has_permission_to?('delete_products') %>
        <%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'small alert button' %>
      <% end %>
	</div>
	<% end %>
</div>

<h1><%= @product.name %></h1>

<% if has_permission_to?('post_implementations') %>
	<%= render :partial => 'usage' %>
<% end %>
<%= render :partial => 'usages' %>

<% if @product.comments.count > 0 || logged_in? %>
	<h3>Comments</h3>

	<%= render :partial => 'comments/comments' %>
	<%= render :partial => 'comments/form' %>
<% end %>